import os
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import datetime

def get_db():
    """
    Connects to MongoDB and returns the database object.
    """
    uri = os.getenv("MONGODB_URI")
    if not uri:
        raise ValueError("MONGODB_URI environment variable not set.")
    
    client = MongoClient(uri, server_api=ServerApi('1'))
    
    try:
        client.admin.command('ping')
        print("Pinged your deployment. You successfully connected to MongoDB!")
    except Exception as e:
        print(e)
        return None

    return client['resolutes']

def save_startup_data(startup_name, extracted_text, gemini_json):
    """
    Saves startup data to the 'startups' collection in MongoDB.

    Args:
        startup_name (str): The name of the startup.
        team_name (str): The name of the team.
        extracted_text (str): The text extracted from uploaded documents.
        gemini_json (dict): The JSON data generated by Gemini.

    Returns:
        The ID of the inserted document.
    """
    db = get_db()
    if db is None:
        return None
        
    startup_document = {
        "startup_name": startup_name,
        "original_extracted_text": extracted_text,
        "gemini_analysis": gemini_json,
        "timestamp": datetime.datetime.utcnow()
    }
    
    result = db.startups.insert_one(startup_document)
    return result.inserted_id
